export enum ACTIONS {
  SET_ROBOT = "SET_ROBOT",
  MOVEX = "MOVEX",
  MOVEY = "MOVEY",
  TURN = "TURN",
  SET_DIMENSION = "SET_DIMENSION",
  SET_COMMANDS = "SET_COMMANDS",
  SET_ERROR = "SET_ERROR",
  IS_PLACED = "IS_PLACED",
}
